services:
  postgres:
    image: postgres:15
    container_name: gamebook_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamebookdb
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

volumes:
  pg-data: